// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CareerSavegameIntroductionHelp } from "./CareerSavegameIntroductionHelp";
import type { CareerSavegameMap } from "./CareerSavegameMap";
import type { CareerSavegameMapsSplitShapeFileIds } from "./CareerSavegameMapsSplitShapeFileIds";
import type { CareerSavegameMod } from "./CareerSavegameMod";
import type { CareerSavegameSettings } from "./CareerSavegameSettings";
import type { CareerSavegameSlotSystem } from "./CareerSavegameSlotSystem";
import type { CareerSavegameStatistics } from "./CareerSavegameStatistics";
import type { Farms } from "./Farms";

export type CareerSavegame = { settings: CareerSavegameSettings, map: CareerSavegameMap, introductionHelp: CareerSavegameIntroductionHelp, statistics: CareerSavegameStatistics, mapsSplitShapeFileIds: CareerSavegameMapsSplitShapeFileIds, slotSystem: CareerSavegameSlotSystem, mod: Array<CareerSavegameMod>, farms: Farms | null, };
