// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CareerSavegameIntroductionHelp = { active: boolean, shownElements: string | null, shownHints: string | null, };
