// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CareerSavegameMod = { modName: string, title: string, version: string, required: boolean, fileHash: string, };
