// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FarmsFinances } from "./FarmsFinances";
import type { FarmsPlayers } from "./FarmsPlayers";
import type { FarmsStatistics } from "./FarmsStatistics";

export type FarmsFarm = { farmId: number, name: string, color: number, loan: number, money: number, players: FarmsPlayers, statistics: FarmsStatistics, finances: FarmsFinances, };
