// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModDescExtraSourceFile } from "./ModDescExtraSourceFile";

export type ModDescExtraSourceFiles = { sourceFile: Array<ModDescExtraSourceFile>, };
