// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModDescDescription } from "./ModDescDescription";
import type { ModDescExtraSourceFiles } from "./ModDescExtraSourceFiles";
import type { ModDescMultiplayer } from "./ModDescMultiplayer";
import type { ModDescStoreItems } from "./ModDescStoreItems";
import type { ModDescTitle } from "./ModDescTitle";

export type ModDesc = { descVersion: number, author: string, version: string, title: ModDescTitle, description: ModDescDescription, iconFilename: string, multiplayer: ModDescMultiplayer, storeItems: ModDescStoreItems, extraSourceFiles: ModDescExtraSourceFiles, };
