name: "publish"

on:
  push:
    branches:
      - release

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  pre-release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest" # for Arm based macs (M1 and above).
          #   args: "--target aarch64-apple-darwin"
          # - platform: "macos-latest" # for Intel based macs.
          #   args: "--target x86_64-apple-darwin"
          # - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
          #   args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

          
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          AZURE_TENANT_ID: ${{ matrix.platform == 'windows-latest' && secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ matrix.platform == 'windows-latest' && secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ matrix.platform == 'windows-latest' && secrets.AZURE_CLIENT_SECRET }}
        with:
          # includeRelease: false
          # tagName: app-v__VERSION__
          # releaseName: "v__VERSION__"
          # releaseBody: ${{ steps.create-release-notes.outputs.release-notes }}
          # releaseDraft: false
          # prerelease: false
          args: ${{ matrix.args }} 
      
      - name: Sign Binaries with Trusted Signing
        uses: azure/trusted-signing-action@v0.3.19
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: ${{ secrets.AZURE_ENDPOINT }}
          trusted-signing-account-name: ${{ secrets.AZURE_CODE_SIGNING_NAME }}
          certificate-profile-name:  ${{ secrets.AZURE_CERT_PROFILE_NAME }}
          files-folder: ${{ github.workspace }}\src-tauri\target\${{ matrix.target }}\release\bundle\nsis\
          files-folder-depth: 7
          files-folder-filter: exe
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Collect Distribution Binaries
        env:
          PLATFORM: ${{ matrix.os }}
        run: ./scripts/collect-binaries.sh
        shell: bash

      - name: Upload Distribution Binaries
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: ${{ github.workspace }}/artifacts/*

  release:
    permissions:
      contents: write
    needs: pre-release
    runs-on: ubuntu-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4

      - name: Tag Release
        uses: jaywcjlove/create-tag-action@main
        id: tag_release
        with:
          release: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}
            
            ${{ steps.changelog.outputs.changelog }}

      - name: Download Distribution Binaries
        uses: actions/download-artifact@v4
        if: steps.tag_release.outputs.successful == 'true'
        with:
          path: artifacts
          merge-multiple: true

      - name: Generate changelog
        uses: jaywcjlove/changelog-generator@main
        if: steps.tag_release.outputs.successful == 'true'
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release App
        uses: softprops/action-gh-release@v2
        if: steps.tag_release.outputs.successful == 'true'
        with:
          tag_name: ${{ steps.tag_release.outputs.version }}
          name: ${{ steps.tag_release.outputs.version }}
          body: |
            ${{ steps.changelog.outputs.compareurl }}

            ${{ steps.changelog.outputs.changelog }}
          files:
            ${{ github.workspace }}/artifacts/**/*
