name = "farm-station-25"
main = "src/index.ts"
compatibility_date = "2025-01-15"
minify = true
account_id = "d9ecce8bbe39fe364970386ffeb65967"

r2_buckets = [
  { binding = "LS25", bucket_name = "ls25", jurisdiction = "eu" }
]


kv_namespaces = [
  { id = "dfc57538627b4f748a70030ccbba57f0", binding = "LS25DATA" }
]


[observability.logs]
enabled = true